defaults:
  - files: mnist
  - _self_
paths:
  log: ./runs
  data: ${hydra:runtime.cwd}/../data/raw
experiment:
  experiment_name: train_UNet
  out_dir: ./outputs/
  starting_checkpoint_path: ./outputs/UNet_all_data_dmg/checkpoints/checkpoint_0.pth.tar
params:
  mode: dmg
  device: cuda:2
  epochs: 1500
  lr: 0.005
  batch_size: 32
  num_chips_to_viz: 1
  labels_dmg: [0, 1, 2, 3, 4],
  labels_bld: [0, 1],
  weights_seg: [1, 15],
  weights_damage: [1, 35, 70, 150, 120],
  weights_loss: [0, 0, 1],
